# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/prompt_builder',
                'doc_host': 'https://algal.github.io',
                'git_url': 'https://github.com/algal/prompt_builder',
                'lib_path': 'prompt_builder'},
  'syms': {'prompt_builder.core': {'prompt_builder.core.foo': ('core.html#foo', 'prompt_builder/core.py')}}}
